// Skeleton class generated by rmic, do not edit.
// Contents subject to change without notice.

package eu.ase.rmiweb;

public final class SampleServerImageImpl_Skel
    implements java.rmi.server.Skeleton
{
    private static final java.rmi.server.Operation[] operations = {
	new java.rmi.server.Operation("byte remoteProcessPictureTime(byte[], java.lang.String, java.lang.String, java.lang.String, java.lang.String, int)[]")
    };
    
    private static final long interfaceHash = 5315442835302670565L;
    
    public java.rmi.server.Operation[] getOperations() {
	return (java.rmi.server.Operation[]) operations.clone();
    }
    
    public void dispatch(java.rmi.Remote obj, java.rmi.server.RemoteCall call, int opnum, long hash)
	throws java.lang.Exception
    {
	if (hash != interfaceHash)
	    throw new java.rmi.server.SkeletonMismatchException("interface hash mismatch");
	
	eu.ase.rmiweb.SampleServerImageImpl server = (eu.ase.rmiweb.SampleServerImageImpl) obj;
	switch (opnum) {
	case 0: // remoteProcessPictureTime(byte[], String, String, String, String, int)
	{
	    byte[] $param_arrayOf_byte_1;
	    java.lang.String $param_String_2;
	    java.lang.String $param_String_3;
	    java.lang.String $param_String_4;
	    java.lang.String $param_String_5;
	    int $param_int_6;
	    try {
		java.io.ObjectInput in = call.getInputStream();
		$param_arrayOf_byte_1 = (byte[]) in.readObject();
		$param_String_2 = (java.lang.String) in.readObject();
		$param_String_3 = (java.lang.String) in.readObject();
		$param_String_4 = (java.lang.String) in.readObject();
		$param_String_5 = (java.lang.String) in.readObject();
		$param_int_6 = in.readInt();
	    } catch (java.io.IOException e) {
		throw new java.rmi.UnmarshalException("error unmarshalling arguments", e);
	    } catch (java.lang.ClassNotFoundException e) {
		throw new java.rmi.UnmarshalException("error unmarshalling arguments", e);
	    } finally {
		call.releaseInputStream();
	    }
	    byte[] $result = server.remoteProcessPictureTime($param_arrayOf_byte_1, $param_String_2, $param_String_3, $param_String_4, $param_String_5, $param_int_6);
	    try {
		java.io.ObjectOutput out = call.getResultStream(true);
		out.writeObject($result);
	    } catch (java.io.IOException e) {
		throw new java.rmi.MarshalException("error marshalling return", e);
	    }
	    break;
	}
	    
	default:
	    throw new java.rmi.UnmarshalException("invalid method number");
	}
    }
}
